/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.fero.manejd;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Manejd classUnderTest = new Manejd();
    }
}
